name: CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libglfw3-dev libglm-dev libopenal-dev
      - name: Configure
        run: cmake -S . -B build -DFETCH_DEPS=ON
      - name: Build
        run: cmake --build build --config Release -j
      - name: Run tests
        run: ctest --test-dir build --output-on-failure

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DFETCH_DEPS=ON
      - name: Build
        run: cmake --build build --config Release


coverage-job:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov build-essential cmake
    - name: Configure with coverage
      run: cmake -S . -B build-coverage -DFETCH_DEPS=ON -DCODE_COVERAGE=ON
    - name: Build
      run: cmake --build build-coverage --config Release -j
    - name: Run tests
      run: ctest --test-dir build-coverage --output-on-failure
    - name: Capture coverage
      run: |
        lcov --directory build-coverage --capture --output-file coverage.info || true
        lcov --remove coverage.info '/usr/*' --output-file coverage.info || true
        lcov --list coverage.info || true
